sudo: required
services:
  - docker

before_install:
  - docker build -t mstandley/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true mstandley/react-test npm test -- --coverage

after_success:
  - docker build -t mstandley/multi-client ./frontend
  - docker build -t mstandley/multi-nginx ./nginx
  - docker build -t mstandley/multi-server ./server
  - docker build -t mstandley/multi-worker ./worker
  # Login to docker CLI (credentials are stored as environment variables in Travis)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mstandley/multi-client
  - docker push mstandley/multi-nginx
  - docker push mstandley/multi-server
  - docker push mstandley/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "marks-multi-docker"
  env: "MarksMultiDocker-env-1"
  bucket_name: "elasticbeanstalk-eu-west-1-146510325632"
  bucket_path: "mark-docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

